### ISSUE TITLE
start_protocol.py - argument experiment-duration acccepted but not used downstream

### ISSUE THREAD

**Issue by neuropathbasel** [nanoporetech/minknow_api#20]
I tried to reduce the runtime from your example from 24 hrs to 1 hour.
In suitable python environment I do run:
$ python start_protocol.py \
> --host localhost --position MN32621 \
> --sample-id "2021_04_28b_cmd_run_01" \
> --experiment-group "2021_04_28b_cmd_run_01" \
> --experiment-duration **1** \
> --basecalling \
> --fastq --bam \
> --verbose \
> --kit SQK-RBK004 \
> --barcoding \
> --barcode-kits "SQK-RBK004"

but in the started protocols I do find the default runtime of 72 hours:
<...>
Starting protocol on 1 positions
Starting protocol sequencing/sequencing_MIN106_DNA:FLO-MIN106:SQK-RBK004 on position MN32621
DEBUG:minknow_api.tools.protocols:Built protocol arguments: --base_calling=on --barcoding barcoding_kits=['SQK-RBK004',] -**-experiment_time=72** --fast5=off --fastq=on --fastq_data compress --fastq_reads_per_file=4000 --bam=on --active_channel_selection=on --mux_scan_period=1.5
Started protocol e39a452b-ee3e-49af-8d68-39d9b0b0f9dc

How can I correct this?

Thanks
Claus

**Comment by jorj1988** [comment]
Hello @neuropathbasel,

There was an issue with the example code which we had fixed in the upcoming release.

I've backported it and tagged `4.2.4` - please try this release.

- George

**Comment by neuropathbasel** [comment]
Hi George,
Many thanks. this works.
I highly appreciate your rapid support.
Claus

**Comment by jorj1988** [comment]
No worries - let us know if you hit further issues!
