### ISSUE TITLE
Incomplete shutdown of MinKNOW experiment when initiating the call from the API (Windows)

### ISSUE THREAD

**Issue by nodrogluap** [nanoporetech/minknow_api#21]
Calling the shutdown function (with any of the three mode options) of the MinKNOW C++ API appears to cause the device to stop (no fan noise, red light on the device), yet in the latest UI the state is still "sequencing", and the voltage chart still shows a voltage being applied.

1. Is this a known issue?
2. How can we check if it's stopped for real, other than the UI?
3. Is there a code table for the device lights?

Thank you!

**Comment by jorj1988** [comment]
Hi @nodrogluap,

Are you able to provide a link to the specific API you are calling?

If you want to end the protocol, you should be invoking: https://github.com/nanoporetech/minknow_api/blob/master/proto/minknow_api/protocol.proto#L20 `stop_protocol`. As far as I am aware minknow does not present a "shutdown" API to users.

Thanks,
- George

**Comment by nodrogluap** [comment]
Hi, calling this method from protocol instead of stop() from the acquisition proto did the trick, thanks!
