### ISSUE TITLE
Cors and minknow_api 

### ISSUE THREAD

**Issue by orel509** [nanoporetech/minknow_api#23]
Hello, I wanted to know if the web version of minknow_api supports CORS or is it not possible to use the minknow_api through different origins?

**Comment by jorj1988** [comment]
Hello @orel509,

We have fixed this in the most recent release, due to ship to customers shortly.

Hope this helps,
- George

**Comment by orel509** [comment]
fixed what? does it supports it now or is it not allowed?

**Comment by orel509** [comment]
> Hello @orel509,
> 
> We have fixed this in the most recent release, due to ship to customers shortly.
> 
> Hope this helps,
> 
>     * George

fixed what? does it support it now or is it not allowed? And do you maybe have an estimated date? thank you in advance.

**Comment by jorj1988** [comment]
The next release will include specific options (`--allow_all_origins`) to all the grpc web proxies (https://github.com/improbable-eng/grpc-web) used to host web grpc connections to minknow. This should fix any CORS issues.

I'm unable to give a date, we are working to ship as quickly as possible.
