### ISSUE TITLE
possible to derive ID of Flowcell?

### ISSUE THREAD

**Issue by neuropathbasel** [nanoporetech/minknow_api#26]
Hello,
is it currently possible to pass the ID of an inserted Flowcell into a variable?
Looking forward to your reply & best wishes
Claus

**Comment by jorj1988** [comment]
Hello,

Please see `get_flow_cell_info` here: https://github.com/nanoporetech/minknow_api/blob/master/proto/minknow_api/device.proto#L48

and the `flow_cell_id` field here: https://github.com/nanoporetech/minknow_api/blob/master/proto/minknow_api/device.proto#L470

I hope that helps?

Thanks,
- George

**Comment by neuropathbasel** [comment]
Thanks for your rapid reply. I could not dedicate too much time on this. But so far I am not really clear how to use the device.proto file from python to derive the flowcell id. I could not find the lines you mentioned in device_pb2.py or device.py.

I will try to follow this up middle of next week.

**Comment by neuropathbasel** [comment]
thanks, I think we figured this out.
