### ISSUE TITLE
how can we modify the start_protocol.py to obtain zlib_compres fast5

### ISSUE THREAD

**Issue by neuropathbasel** [nanoporetech/minknow_api#28]
We did not find a switch to define zlib_compres fast5 as output option and do seem to obtain (by default?)  vbz_compres fast5.
Essentially we would like to obtain fast5 identical to those generated by starting a run with MinKnow UI. Currently we do use the SQK-RBK004 kit.
Looking forward to your reply.
Best wishes
Claus

**Comment by jorj1988** [comment]
Hello, you would need to adjust this line: 

https://github.com/nanoporetech/minknow_api/blob/master/python/minknow_api/tools/protocols.py#L316:
```python

    if fast5_arguments:
        protocol_args.extend(
            ["--fast5_data", "trace_table", "fastq", "raw", "vbz_compress"] # zlib_compress instead of vbz_compress here

```

VBZ is become the default with MinKNOW UI, in the latest release so these are now in sync. I will raise the ability to configure this option from the script with the development group.

**Comment by neuropathbasel** [comment]
Thanks! We had tried this yesterday with success - but I thought there was a different way, other than modifying the protocols.py script. Best, Jürgen
