### ISSUE TITLE
Access to flow cell check data

### ISSUE THREAD

**Issue by mwbudde** [nanoporetech/minknow_api#40]
It would be very helpful if we can access (or control entirely) the flow cells check via API. Is that feasible? Even being able to scrape the historical data from the computer or via a web protocol would be great.

**Comment by jorj1988** [comment]
Hi @mwbudde,

I think what youre asking for is exactly what this project is for, see the example here: https://github.com/nanoporetech/minknow_api/blob/master/python/minknow_api/examples/extract_run_statistics.py about extracting run data from historical runs.

If you have a specific issue please feel free to post a problem - and I can assist.

- George

**Comment by mwbudde** [comment]
Excellent, thank you, George!

**Comment by mwbudde** [comment]
Hi George, thanks again for your help.

We can now get the flow cell check pore data using the method in that example.

Is there a way to get pore data from historical runs, sim
