### ISSUE TITLE
longle flowcell not detectable

### ISSUE THREAD

**Issue by YingziZhang-github** [nanoporetech/minknow_api#51]
Dear Nanoporetech,

I am a MinION user. Recently, I have been trying flongle flow cells in our lab.
Our MinKNOW software (v22.05.5) always cannot detect the flongle flowcells (I've tried several flongles). However, I tried the adapter and the flongles with another GridION with another workstation (MinKNOW v.22.12.5) and that worked very well. The user of the working workstation told me that she met with the same issue before and it was solved by restarting MinKNOW. However, I failed to copy the troubleshooting method. Would you please let me know your suggestions?

Btw, I wondered if it is because of the minor difference of the MinKNOW version. I tried to update our MinKNOW version by the command "sudo apt install minion-nc", but it reported that minion-nc is already the newest version (22.05.5-1~bionic).

Looking forward to hearing from you.

Best,
Yingzi

**Comment by cjw85** [comment]
Hi @YingziZhang-github,

This issue forum is specifically for support with the MinKNOW API software project.

Your issue will be better dealt with by contacting support@nanoporetech.com.
