### ISSUE TITLE
Setting min_qscore for live basecalling with the current minknow_api version

### ISSUE THREAD

**Issue by thalljiscience** [nanoporetech/minknow_api#52]
In a previous version of minknow (21.11.9, running in Ubuntu 18.04), the following configuration for read_filtering appeared in the sequencing config file /opt/ont/minknow/conf/package/sequencing/sequencing_MIN106_DNA.toml:

<code>[basecaller_configuration.read_filtering]
min_qscore = 7</code>

This configuration is not present in the default installation of minknow version 22.12.7 on Ubuntu 20.04.6, so calls to start_protocol.py with the minknow_api invaraibly default to min_qscore of 0 with version 22.12.7, regardless of the default settings in /opt/ont/guppy/data/dna_r9.4.1_450bps_fast.cfg

It turns out that the default for basecaller_configuration.read_filtering.min_qscore can be added back into sequencing_MIN106_DNA.toml and still works with the current minknow_api, but I was wondering:

How can code be added to start.protocol.py to allow modifying the min_qscore setting dynamically when starting a sequencing run?  I am assuming there is a way to do this and I can just not figure out the syntax.

Any help would be appreciated.

**Comment by jorj1988** [comment]
Hello @thalljiscience ,

There isn't currently a specific command line argument for setting q score in the example, but I'll look at adding one for a future release.

You can specify extra arguments to the `start_protocol.py` script, so:

`start_protocol.py [normal_args] -- --read_filtering min_qscore=10`


Thanks,
- George

**Comment by thalljiscience** [comment]
Very nice!  Thank you!  I actually tried what I thought was exactly that with no effect (--read_filtering min_qscore=7) at the end of my start_protocol.py call (based upon looking at how it was formatted running though MinKNOW UI by calling sudo ps aux).  However, I didn't realize I needed to precede the call with an addition '--'.

Thank you for such a quick reply.  This worked perfectly.
