### ISSUE TITLE
Minknow API Use

### ISSUE THREAD

**Issue by WJohnTao** [nanoporetech/minknow_api#57]
Recently, while using  minknow software（minknow core 5.5.5）, I tried to start sequencing through API (Version is 5.5.2) control and the minknow reported the error as below "Thls verslon of the MInKNOW APl Is no longer supported.Please update to the latest MinKNOoW verslon and try agaln." .So I would like to inquire about how to solve it.

**Comment by jorj1988** [comment]
Hi @WJohnTao ,

Can you provide me more details on the error you received? A screenshot or copy paste of the error would be great.

Thanks,
- George

**Comment by WJohnTao** [comment]
At 2023-07-21 15:37:39, "jorj1988" ***@***.***> wrote:

Hi @WJohnTao ,

Can you provide me more details on the error you received? A screenshot or copy paste of the error would be great.

Thanks,

George

**Comment by jorj1988** [comment]
@WJohnTao

I dont quite follow your comment - can you provide the error message?

Thanks,
- George

**Comment by WJohnTao** [comment]
the minknow software reported the error as below "Thls verslon of the MInKNOW APl Is no longer supported.Please update to the latest MinKNOoW verslon and try agaln."

**Comment by jorj1988** [comment]
Hi @WJohnTao , 

Thanks, but I need a little more info on where this message is coming from - it seems the above message is not copied and pasted but is manually typed in, and I can't see where it originates. What is the exact message you receive, and what script do you run to trigger the error?

Can you provide me a screenshot or exact script/command line interaction to trigger the issue?

Thanks,
- George

**Comment by jorj1988** [comment]
Hi @WJohnTao,

A related internal issue just came up with an exact error message - I've had a look and confirmed it means a minknow_api ~= 5.4 is being used against minknow >= 5.5.

If you update minknow_api to 5.5+ (matching your minknow version) you will be ok.

https://pypi.org/project/minknow-api/

Thanks,
- George
